#!/usr/bin/env bash
set -e -u -o pipefail
export JAVA_HOME="/Library/Java/JavaVirtualMachines/graalvm-jdk-20.0.1+9.1/Contents/Home"
export PATH="/Library/Java/JavaVirtualMachines/graalvm-jdk-20.0.1+9.1/Contents/Home/bin:$PATH"
clojure -X:build uberjar
native-image -jar target/monotony.jar \
    --features=InitAtBuildTimeFeature \
    -H:IncludeResources='.*\.(g4|edn|tokens|clj|st|stg|MF)$' \
    --no-fallback target/monotony \
    --enable-url-protocols=https \
    --verbose \
    -ea \
    --initialize-at-build-time='org.stringtemplate.v4.STGroup,org.antlr.v4.runtime.atn.RuleTransition,org.antlr.v4.runtime.atn.StarLoopbackState,org.antlr.v4.runtime.atn.EpsilonTransition,org.antlr.v4.runtime.atn.PlusLoopbackState,org.antlr.v4.runtime.atn.SetTransition,org.antlr.v4.runtime.atn.ATNState,org.antlr.v4.runtime.atn.RuleStartState,org.antlr.v4.runtime.atn.ActionTransition,org.antlr.v4.runtime.Recognizer,org.antlr.v4.runtime.atn.PlusBlockStartState,org.antlr.v4.codegen.Target,org.antlr.v4.Tool,org.stringtemplate.v4.STGroupFile,org.stringtemplate.v4.compiler.GroupLexer,org.stringtemplate.v4.compiler.Compiler,org.antlr.v4.runtime.atn.BlockEndState,org.antlr.v4.tool.Rule,org.antlr.v4.runtime.atn.PrecedencePredicateTransition,org.antlr.v4.runtime.atn.AbstractPredicateTransition,org.antlr.v4.runtime.atn.TokensStartState,org.antlr.v4.parse.ANTLRLexer,org.antlr.v4.runtime.atn.RuleStopState,org.antlr.v4.automata.LexerATNFactory$1,org.antlr.v4.runtime.atn.Transition,org.antlr.v4.tool.ast.GrammarRootAST,org.antlr.v4.tool.LexerGrammar,org.antlr.v4.runtime.Parser,org.antlr.v4.runtime.atn.StarLoopEntryState,org.antlr.v4.tool.AttributeDict,org.antlr.v4.tool.LeftRecursiveRule,org.antlr.v4.runtime.atn.NotSetTransition,org.antlr.v4.runtime.atn.DecisionState,org.antlr.v4.tool.ErrorType,org.antlr.v4.automata.LexerATNFactory,org.antlr.v4.runtime.atn.BasicBlockStartState,org.antlr.v4.runtime.atn.StarBlockStartState,org.antlr.v4.runtime.atn.AtomTransition,org.antlr.v4.tool.Grammar,org.stringtemplate.v4.Interpreter,org.antlr.v4.parse.ToolANTLRLexer,org.antlr.v4.automata.LexerATNFactory$CharSetParseState,org.antlr.v4.runtime.atn.WildcardTransition,org.antlr.v4.runtime.atn.BasicState,org.antlr.v4.runtime.atn.EmptyPredictionContext,org.stringtemplate.v4.misc.Misc,org.antlr.v4.runtime.atn.BlockStartState,org.antlr.v4.runtime.atn.LoopEndState,org.antlr.v4.runtime.misc.IntervalSet,org.antlr.v4.semantics.BasicSemanticChecks,org.antlr.v4.parse.LeftRecursiveRuleWalker,org.antlr.v4.parse.ATNBuilder,org.antlr.v4.semantics.SymbolCollector,org.stringtemplate.v4.compiler.CodeGenerator,org.antlr.v4.semantics.RuleCollector,org.antlr.v4.Tool$1UndefChecker,org.antlr.v4.parse.BlockSetTransformer,org.antlr.v4.parse.GrammarTreeVisitor,org.antlr.runtime.tree.TreeRewriter,org.antlr.v4.analysis.LeftRecursiveRuleAnalyzer,org.antlr.runtime.tree.TreeParser'

/bin/cp -f target/monotony /usr/local/bin/monotony